// Original practice material. Not textbook excerpts.
const data = [
['认识新朋友','从一句问候开始','☀',
[['Hi, I’m Alex. Nice to meet you.','你好，我是 Alex。很高兴认识你。'],['Nice to meet you, too. I’m Sam.','我也很高兴认识你。我是 Sam。'],['Where do you live?','你住在哪里？'],['I live in Shanghai. How about you?','我住在上海。你呢？']],
[['Nice to meet you.','很高兴认识你。','第一次见面时使用。'],['I live in Shanghai.','我住在上海。','把 Shanghai 换成你所在的城市。'],['How about you?','你呢？','回答后反问，让聊天继续。']],
['Sam 住在哪里？',['上海','北京','没有提到'],0,'Sam 说：I live in Shanghai.'], '介绍自己住在哪里，再问对方。'],
['聊聊一天','说说你的日常','◷',
[['What do you usually do after work?','你下班后通常做什么？'],['I usually go for a walk.','我通常去散步。'],['That sounds nice. Do you cook dinner?','听起来不错。你做晚饭吗？'],['Yes, I do. How about you?','是的，我做。你呢？']],
[['What do you usually do after work?','你下班后通常做什么？','usually 表示通常；不工作时可把 after work 换成 in the evening。'],['I usually go for a walk.','我通常去散步。','go for a walk 表示去散步。'],['That sounds nice.','听起来不错。','对别人刚说的事情做出回应。']],
['对方下班后通常做什么？',['去购物','去散步','打电话'],1,'go for a walk 表示去散步。'],'说说你晚上通常做的事情。'],
['兴趣爱好','找到共同话题','♫',
[['What do you like to do in your free time?','你空闲时喜欢做什么？'],['I like listening to music.','我喜欢听音乐。'],['Me too! What kind of music do you like?','我也是！你喜欢哪种音乐？'],['I like pop music.','我喜欢流行音乐。']],
[['I like listening to music.','我喜欢听音乐。','like 后可以接动词的 -ing 形式。'],['Me too!','我也是！','表达你有相同的喜好。'],['What kind of music do you like?','你喜欢哪种音乐？','What kind of ... 询问种类。']],
['对方喜欢哪种音乐？',['古典音乐','爵士乐','流行音乐'],2,'pop music 是流行音乐。'],'说一种爱好，再问对方喜欢哪一种。'],
['咖啡店点单','点一杯你喜欢的','☕',
[['Hi, what can I get for you?','你好，想喝点什么？'],['I’d like a cup of tea, please.','我想要一杯茶，谢谢。'],['Hot or iced?','热的还是冰的？'],['Hot, please. To go, please.','热的，谢谢。请打包带走。']],
[['I’d like a cup of tea, please.','我想要一杯茶，谢谢。','I’d like 是 I would like 的缩写，礼貌地表达想要。'],['Hot, please.','热的，谢谢。','也可以说 Iced, please.'],['To go, please.','请打包带走。','说明要带走，不在店内喝。']],
['顾客要什么饮品？',['热茶','冰咖啡','果汁'],0,'a cup of tea 加上 Hot 表示热茶。'],'点一种你喜欢的饮品，说明冷热。'],
['餐厅用餐','从点餐到结账','♧',
[['Are you ready to order?','您准备好点餐了吗？'],['What do you recommend?','你推荐什么？'],['The chicken soup is very good.','鸡汤很好喝。'],['I’ll have the soup, please.','请给我来份汤。'],['Anything else?','还需要别的吗？'],['No, thank you. Could I have the bill, please?','不用了，谢谢。请给我账单好吗？']],
[['What do you recommend?','你推荐什么？','不知道点什么时，可以请对方推荐。'],['I’ll have the soup, please.','请给我来份汤。','点餐时 I’ll have ... 表示我选……。'],['Could I have the bill, please?','请给我账单好吗？','礼貌地请求结账。']],
['店员推荐了什么？',['沙拉','鸡汤','面包'],1,'The chicken soup is very good. 是推荐鸡汤。'],'用 I’ll have ... 点一道自己喜欢的菜。'],
['购物询问','选到合适的东西','▧',
[['Can I help you?','有什么可以帮您的吗？'],['How much is this shirt?','这件衬衫多少钱？'],['It’s twenty dollars.','二十美元。'],['Do you have it in blue?','这款有蓝色的吗？'],['Yes. What size do you need?','有。您需要什么尺码？'],['Can I try a medium?','我可以试一下中码吗？']],
[['How much is this shirt?','这件衬衫多少钱？','How much is ... 询问单件物品的价格。'],['Do you have it in blue?','这款有蓝色的吗？','in blue 表示蓝色款。'],['Can I try a medium?','我可以试一下中码吗？','medium 是中码，也可换成 small 或 large。']],
['顾客想要什么颜色？',['黑色','白色','蓝色'],2,'in blue 表示蓝色。'],'问一件物品的价格，再说想要的颜色。'],
['问路','把目的地说明白','↗',
[['Excuse me. Where is the station?','打扰一下，车站在哪里？'],['Go straight and turn left.','直走，然后左转。'],['Is it far from here?','离这里远吗？'],['No, it’s about five minutes on foot.','不远，步行大约五分钟。']],
[['Excuse me. Where is the station?','打扰一下，车站在哪里？','先说 Excuse me 更礼貌。'],['Is it far from here?','离这里远吗？','far 表示远。'],['Go straight and turn left.','直走，然后左转。','turn right 则是右转。']],
['应该往哪个方向转？',['左转','右转','掉头'],0,'turn left 是左转。'],'询问附近一个地点在哪里、远不远。'],
['日常出行','轻松确认行程','⇢',
[['Where would you like to go?','您想去哪里？'],['Could you take me to the station?','你能送我去车站吗？'],['Of course.','当然可以。'],['How long does it take?','需要多长时间？'],['About twenty minutes.','大约二十分钟。'],['Thank you. Please stop here.','谢谢。请在这里停车。']],
[['Could you take me to the station?','你能送我去车站吗？','把 the station 换成你的目的地。'],['How long does it take?','需要多长时间？','How long 询问时长。'],['Please stop here.','请在这里停车。','到达目的地时使用。']],
['行程大约需要多久？',['十分钟','二十分钟','一小时'],1,'twenty minutes 是二十分钟。'],'告诉司机你想去哪里，并询问要多久。'],
['天气闲聊','随时能聊的小话题','☁',
[['It’s a lovely day, isn’t it?','天气真好，是吧？'],['Yes, it is. It’s warm today.','是啊，今天很暖和。'],['Do you want to go for a walk?','你想去散步吗？'],['Sure. Let’s go to the park.','好啊。我们去公园吧。']],
[['It’s warm today.','今天很暖和。','warm 可以换成 cold、hot 或 cool。'],['Do you want to go for a walk?','你想去散步吗？','Do you want to ... 询问对方是否想做某事。'],['Let’s go to the park.','我们去公园吧。','Let’s 后面接动词原形，提出一起做某事。']],
['两人准备去哪里？',['商店','车站','公园'],2,'Let’s go to the park. 是提议去公园。'],'描述今天的天气，提出一个适合的活动。'],
['昨天的生活','把一件小事说出来','↶',
[['How was your day yesterday?','你昨天过得怎么样？'],['It was good. I went shopping.','挺好的。我去购物了。'],['Did you buy anything?','你买什么了吗？'],['Yes, I bought a book.','买了，我买了一本书。']],
[['How was your day yesterday?','你昨天过得怎么样？','was 是 is 的过去式。'],['I went shopping.','我去购物了。','went 是 go 的过去式，用来讲过去的事。'],['I bought a book.','我买了一本书。','bought 是 buy 的过去式。']],
['对方昨天买了什么？',['一本书','一件衬衫','一杯茶'],0,'I bought a book. 表示买了一本书。'],'说一件你昨天做过的小事。'],
['周末计划','聊聊还没发生的事','□',
[['Do you have any plans for the weekend?','你周末有什么计划吗？'],['I’m going to visit a friend.','我准备去看一位朋友。'],['That sounds fun.','听起来很有意思。'],['What about you?','你呢？']],
[['Do you have any plans for the weekend?','你周末有什么计划吗？','plans 表示计划。'],['I’m going to visit a friend.','我准备去看一位朋友。','be going to 后接动词原形，表达打算。'],['That sounds fun.','听起来很有意思。','用来回应对方的活动计划。']],
['对方周末准备做什么？',['去上班','看望朋友','搬家'],1,'visit a friend 是看望朋友。'],'说一个周末计划，再问对方。'],
['发出邀请','一起喝杯咖啡吧','♡',
[['Would you like to have coffee on Saturday?','你周六愿意一起喝咖啡吗？'],['I’d love to, but I’m busy on Saturday.','我很想去，但周六有事。'],['How about Sunday?','周日怎么样？'],['Sunday works for me.','周日我可以。']],
[['Would you like to have coffee?','你愿意一起喝咖啡吗？','Would you like to ... 是礼貌的邀请。'],['I’d love to, but I’m busy.','我很想去，但我有事。','先表达意愿，再礼貌说明无法参加。'],['Sunday works for me.','周日我可以。','works for me 表示这个安排对我合适。']],
['最终约定的是哪一天？',['周五','周六','周日'],2,'Sunday works for me. 接受了周日的安排。'],'邀请朋友一起做一件事，并约一个时间。'],
['表达需要','有困难时也能开口','✦',
[['Excuse me. Could you help me?','打扰一下，你能帮我一下吗？'],['Of course. What’s the problem?','当然。有什么问题？'],['I can’t find my bag.','我找不到我的包了。'],['What color is it?','它是什么颜色？'],['Could you say that again?','你能再说一遍吗？'],['What color is your bag?','你的包是什么颜色？']],
[['Could you help me?','你能帮我一下吗？','Could you ... 是礼貌的请求。'],['I can’t find my bag.','我找不到我的包了。','can’t 是 cannot 的缩写。'],['Could you say that again?','你能再说一遍吗？','没听清时可以直接使用。']],
['对方遇到了什么问题？',['找不到包','错过了车','忘了带钱'],0,'can’t find my bag 表示找不到包。'],'说一个需要帮助的情况，听不清时请对方重复。'],
['把聊天接下去','从问候到自然结束','…',
[['How’s your day going?','你今天过得怎么样？'],['Pretty good. I tried a new restaurant.','挺好的。我去尝试了一家新餐厅。'],['Really? How was it?','是吗？怎么样？'],['The food was great.','饭菜很棒。'],['That sounds nice. It was nice talking to you.','听起来不错。和你聊天很开心。'],['You too. See you later!','我也是。回头见！']],
[['How’s your day going?','你今天过得怎么样？','日常问候，询问今天到目前为止的情况。'],['Really? How was it?','是吗？怎么样？','追问一个细节，让对方继续讲。'],['It was nice talking to you.','和你聊天很开心。','自然结束一次交谈。']],
['对方觉得餐厅的饭菜怎么样？',['一般','很棒','太冷'],1,'The food was great. 表示饭菜很棒。'],'聊一件最近发生的小事，并自然结束聊天。']
];
export const lessons=data.map((d,i)=>({id:`lesson-${i+1}`,title:d[0],subtitle:d[1],icon:d[2],dialogue:d[3].map(([en,zh],j)=>({speaker:j%2?'B':'A',en,zh})),expressions:d[4].map(([en,zh,note],j)=>({id:`l${i+1}-e${j+1}`,en,zh,note,tokens:en.split(' ')})),question:{prompt:d[5][0],options:d[5][1],answerIndex:d[5][2],explanation:d[5][3]},personalPrompt:d[6]}));
export const getLesson=id=>lessons.find(l=>l.id===id);
export const expressions=Object.fromEntries(lessons.flatMap(l=>l.expressions.map(e=>[e.id,e])));
